version: "3.8"
services:
  web:
    image: covid
    build: .
    command: "node app.js"
    ports:
      - "4000:4000"
    depends_on: 
        - "mongo"
  mongo:
    image : "mongo"
    ports:
      - "27017:27017"
    restart: unless-stopped